name: Tests ðŸ§ª
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Run unit tests
        run: npm run test:unit
  cypress-run-local:
    runs-on: ubuntu-24.04
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run local
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_LOCAL_CREDENTIALS: "${{ secrets.CYPRESS_LOCAL_CREDENTIALS }}"
        with:
          command: npm run start:server:and:test:local
      - name: Save screenshots in case of failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-local
          path: cypress/screenshots
          if-no-files-found: ignore

  cypress-run-test:
    runs-on: ubuntu-24.04
    needs: cypress-run-local
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run test
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_TEST_CREDENTIALS: "${{ secrets.CYPRESS_TEST_CREDENTIALS }}"
        with:
          command: npm run cy:run:test
      - name: Save screenshots in case of failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-test
          path: cypress/screenshots
          if-no-files-found: ignore

  cypress-run-staging:
    runs-on: ubuntu-24.04
    needs: cypress-run-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run staging
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_STAGING_CREDENTIALS: "${{ secrets.CYPRESS_STAGING_CREDENTIALS }}"
        with:
          command: npm run cy:run:staging
      - name: Save screenshots in case of failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-staging
          path: cypress/screenshots
          if-no-files-found: ignore

  cypress-run-prod:
    runs-on: ubuntu-24.04
    needs: cypress-run-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run prod
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_PROD_CREDENTIALS: "${{ secrets.CYPRESS_PROD_CREDENTIALS }}"
        with:
          command: npm run cy:run:prod
      - name: Save screenshots in case of failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-prod
          path: cypress/screenshots
          if-no-files-found: ignore
